### PR TITLE
impl. register_finalizer, force_collect

### PR DESCRIPTION
**Pull request by yhara**
This PR adds wrapper for GC_gcollect and GC_register_finalizer.
(Please let me know if you prefer another name for wrappers)

### CODE REVIEW

**Comment by raviqqe** [comment]
Thank you for your contribution!

**Comment by raviqqe** [comment]
Do you think the `client_data` and `finalizer` pair can be a Rust closure? Do you have any public code for the use cases of `GC_register_finalizer()`?

These callback and custom data pairs can often be translated into closures in Rust when building FFI. But I don't know if this is the case...

**Comment by yhara** [comment]
It is possible to change it take a closure like this. However how can we cast `F` to `extern "C" fn(*mut c_void, *mut c_void)`?

```rust
    pub unsafe fn register_finalizer<F>(                                           
        obj: *const c_void,                                                        
        client_data: *const c_void,
        f: F,
    ) where
        F: Fn(*mut c_void, *mut c_void),
    {   
        GC_register_finalizer(obj, f, client_data, std::ptr::null(), std::ptr::null());
    } 
```

**Comment by raviqqe** [comment]
Like #256. But it turned out to require an allocation if we want to cover all general cases... It's probably better to keep the current implementation.

**Pull request merged**
